const data = [
	{
	  id: 1,
	  name: "Mysore",
	  state: "Karnataka",
	  info: "Mysore Palace is a historical palace and a royal residence (house). It is located in Mysore, Karnataka, India. It used to be the official residence of the Wadiyar dynasty and the seat of the Kingdom of Mysore. The palace is in the centre of Mysore, and faces the Chamundi Hills eastward",
	  image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Mysore_Palace_Morning.jpg",
	  price: "95,000",
	},
	{
	  id: 2,
	  name: "Jaipur",
	  state: "Rajasthan",
	  info: "Jaipur is the capital city of the Indian state of Rajasthan, known for its stunning pink-hued buildings and palaces. The city is also known as the due to the color of many of its buildings. Jaipur is famous for its intricate textiles, colorful handicrafts, and delicious cuisine.",
	  image: "https://cdn.thecodehelp.in/Jaipur.jpeg",
	  price: "82,560",
	},
	{
	  id: 3,
	  name: "Goa",
	  state: "Goa",
	  info: "Goa is a small state on India's western coast, known for its stunning beaches, vibrant nightlife, and Portuguese-influenced architecture. The state is also known for its spicy seafood dishes and unique cultural traditions. its famous beaches, culture, climate, and historical places. .",
	  image: "https://cdn.thecodehelp.in/Goa.jpeg",
	  price: "29,695",
	},
	{
	  id: 4,
	  name: "Varanasi",
	  state: "Uttar Pradesh",
	  info: "Varanasi is a holy city in northern India, situated on the banks of the sacred river Ganges. The city is a major pilgrimage site for Hindus and is famous for its ancient temples, winding alleyways, and colorful festivals.",
	  image: "https://cdn.thecodehelp.in/Varanasi.jpeg",
	  price: "31,095",
	},
	{
	  id: 5,
	  name: "Darjeeling",
	  state: "West Bengal",
	  info: "Starting in the colorful port city of Gdańsk, you'll escape the crowds and embrace the understated elegance of ready-for-prime-time Poland for 10 days.It is usually around 25°C and it is indeed the best time to visit Darjeeling. ",
	  image: "https://cdn.thecodehelp.in/Darjeeling.jpeg",
	  price: "78,595",
	},
	{
	  id: 6,
	  name: "Jaisalmer",
	  state: "Rajasthan",
	  info: "Jaisalmer is a city in the Indian state of Rajasthan, known for its stunning sandstone architecture and its location in the heart of the Thar Desert. The city is home to several impressive palaces.The city's most prominent landmark is the Jaisalmer Fort.",
	  image: "https://cdn.thecodehelp.in/Jaisalmer.jpeg",
	  price: "68,595",
	},
	{
	  id: 7,
	  name: "Kochi",
	  state: "Kerala",
	  info: "Kochi is a port city in the Indian state of Kerala, known for its historic connections to trade and commerce. The city is home to several stunning churches, synagogues, and mosques, as well as a rich culinary tradition that blends Indian, Portuguese, and other influences.",
	  image: "https://cdn.thecodehelp.in/Kochi.jpeg",
	  price: "68,595",
	},
	{
		id: 8,
		name: "Mumbai",
		state: "Maharashtra",
		info: "Mumbai is the financial capital of India for its bustling known for its historic connections to trade and commerce. The city is home to several stunning churches, synagogues, and mosques, as well as a rich blends Indian,and other influences influe.",
		image: "https://cdn.pixabay.com/photo/2016/05/03/20/01/mumbai-1370023_1280.jpg",
		price: "50,000",
	  },
	  {
		id: 9,
		name: "Gateway of India",
		state: "Maharashtra",
		info: "The Gateway was later used as a symbolic ceremonial entrance to India for Viceroys and the new Governors of Bombay. It served to allow entry and access to India. The Gateway of India is located on the waterfront at Apollo Bunder area at the end of Chhatrapati Shivaji Marg in Mumbai",
		image: "https://cdn.pixabay.com/photo/2010/11/29/india-294_1280.jpg",
		price: "48,900",
	  },
 
	  {
		id: 10,
		name: "Shimla",
		state: "Himachal Pradesh",
		info: "Shimla is a picturesque hill station in the northern Indian state known for its historic connections to trade and commerce. The city is home to several stunning churches, synagogues, and mosques, as well as  blends Indian, Portuguese, and other.",
		image: "https://www.holidify.com/images/compressed/686.jpg?v=1.1",
		price: "45,000",
	  },
	  {
		id: 11,
		name: "Bodh Gaya",
		state: "Bihar",
		info: "Bodh Gaya is a religious site and place of pilgrimage associated with the Mahabodhi Temple Complex in Gaya district, Bihar, India. It is famous for being the place where Gautama Buddha is said to have attained enlightenment.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mahabodhitemple.jpg/500px-Mahabodhitemple.jpg",
		price: "25,000",
	  },
	  {
		id: 12,
		name: "Hundru Falls",
		state: "Jharkhand",
		info: "Hundru Falls is one of the highest waterfalls in Jharkhand,It is famous for being the place located in Ranchi district. It is a beautiful natural cascade formed on the Subarnarekha River The Hundru Falls is created on Subarnarekha River, .",
		image: "https://cdn.s3waas.gov.in/s32b8a61594b1f4c4db0902a8a395ced93/uploads/bfi_thumb/2018040366-olw7wbs1ybu4s7lagtimonkbz115tox7o2qqt9oway.jpg",
		price: "20,000",
	  },
 
  ];
 
  export default data;